# query {
#   currencyAccounts {
#     id
#     name
#     value
#   }
# }

query currencyAccounts($numberOfHistoryItems: Int!) {
  currencyAccounts(numberOfHistoryItems: $numberOfHistoryItems) {
    id
    name
  }
}

# query {
#   currencies {
#     code
#     symbol
#     historyCourseInUAH {
#       price
#       date
#     }
#   }
# }
