query currencyAccounts($numberOfHistoryItems: Int!) {
  currencyAccounts(numberOfHistoryItems: $numberOfHistoryItems) {
    id
    name
    value
    currency {
      id
      code
    }
    history {
      title
      date
      value
      id
    }
  }
}