query {
  bankcards {
    monobank {
      token
      user {
        firstName
        lastName
      }
      historyCards {
        date
        id
        cards {
          iban
          cardNumber
          balance
          currency {
            code
            historyCourseInUAH {
              price
            }
          }
        }
      }
    }
  }
}

# query {
#   bankcards {
#     monobank {
#       historyCards {
#         cards {
#           balance
#           currency {
#             historyCourseInUAH {
#               price
#             }
#           }
#         }
#       }
#     }
#   }
# }
