query {
  bankcards {
    monobank {
      historyCards {
        cards {
          balance
          currency {
            historyCourseInUAH {
              price
            }
          }
        }
      }
    }
  }
}
